apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: kube-curator-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccount.name }}
  namespace: {{ .Values.namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-deleter
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: kube-curator-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccount.name }}
  apiGroup: ""
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: ""